# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0009_auto_20160712_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='listing_abstract',
            field=models.TextField(blank=True, help_text='Give a brief blurb (about 1 sentence) of what this topic is about. It will appear on other pages that refer to this one.'),
        ),
    ]
