# Generated by Django 3.1.14 on 2022-05-16 20:18

from django.db import migrations, models
import django.db.models.deletion
import project_tier.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('standard', '0023_auto_20220128_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_suffix', models.CharField(blank=True, help_text="Additional text to display after the page title e.g. '(Version 3.0)", max_length=255)),
                ('listing_abstract', models.TextField(blank=True, help_text='Give a brief blurb (about 1 sentence) of what this topic is about. It will appear on other pages that refer to this one.')),
                ('introductory_headline', models.TextField(blank=True, help_text='Introduce the topic of this page in 1-3 sentences.')),
                ('body', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph')), ('bigger_heading', wagtail.core.blocks.TextBlock(icon='fa-header', label='H2', template='blocks/h2.html')), ('heading', wagtail.core.blocks.TextBlock(icon='fa-header', label='H3', template='blocks/h3.html')), ('smaller_heading', wagtail.core.blocks.TextBlock(icon='fa-header', label='H4', template='blocks/h4.html')), ('smallest_heading', wagtail.core.blocks.TextBlock(icon='fa-header', label='H5', template='blocks/h5.html')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.TextBlock(required=False))])), ('download', wagtail.documents.blocks.DocumentChooserBlock(icon='fa-download', template='blocks/download.html')), ('accordion', wagtail.core.blocks.StructBlock([('compact', wagtail.core.blocks.BooleanBlock(help_text='Display a compact accordion for use between paragraphs.', required=False)), ('panels', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(help_text='The headline to display when the accordion panel is closed.')), ('body', wagtail.core.blocks.RichTextBlock(help_text='The inner content of this accordion panel. It is initially hidden.'))], label='Panel')))])), ('notice', wagtail.core.blocks.StructBlock([('message', wagtail.core.blocks.RichTextBlock(help_text='Write the message text.')), ('indicator', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Standard'), ('success', 'Success'), ('alert', 'Alert'), ('warning', 'Warning')], help_text='Choose what type of notice this is.', required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')), ('button', wagtail.core.blocks.StructBlock([('button_target', wagtail.core.blocks.PageChooserBlock(help_text='Choose where this button should link to.', required=False)), ('button_text', wagtail.core.blocks.CharBlock(help_text='What should the button say?', required=False))])), ('simple_flow_boxes', project_tier.blocks.SimpleFlowBlockList()), ('detailed_flow_boxes', project_tier.blocks.DetailedFlowBlockList()), ('periodic_boxes', project_tier.blocks.PeriodicBlockList()), ('highlight_block', wagtail.core.blocks.StructBlock([('body', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph'))])), ('slider_block', wagtail.core.blocks.StructBlock([('slides', wagtail.core.blocks.StreamBlock([('slide', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', required=False)), ('image_or_video', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Choose a horizontal photo', required=False)), ('link', wagtail.core.blocks.URLBlock(help_text='A youtube link to a video', required=False))], blank=False, help_text='Either upload an image, or link to a video. If both fields are present, the video will take precident', required=True))], blank=False, help_text='A single slide'))], blank=True, help_text='Add a slide to the slider'))])), ('hr_block', wagtail.core.blocks.StructBlock([], icon='fa-window-minimize', label='Divider', template='blocks/hr.html')), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.RichTextBlock(help_text='The inner content of this card.'))]), icon='fa-clone', template='blocks/cards.html'))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
