# Generated by Django 3.1.14 on 2023-01-11 18:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0026_auto_20220609_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customindexpage',
            name='custom_sidebar_link',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(max_num=1, required=False)), ('link', wagtail.core.blocks.URLBlock(max_num=1, required=False))], blank=True),
        ),
    ]
