# Generated by Django 2.0.2 on 2018-03-12 04:11

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160621_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='promo_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_cta_text',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
