# Generated by Django 2.1.8 on 2019-12-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_promo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='big_cta_link',
            field=models.URLField(blank=True, verbose_name='Big CTA link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='big_cta_show',
            field=models.BooleanField(default=True, verbose_name='Show big CTA?'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='big_cta_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Big CTA text'),
        ),
    ]
