# Generated by Django 2.1.15 on 2019-12-15 17:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('events', '0009_eventindexpage_intro_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebcastIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True, help_text='An introductory paragraph about the webcast series')),
                ('registration_link', models.URLField(blank=True, help_text='the Zoom registration url')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WebcastPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(help_text='The date of the event', verbose_name='Event date')),
                ('speaker_name', models.CharField(help_text='The name of the speaker', max_length=50, verbose_name='Speaker name')),
                ('talk_title', models.CharField(help_text='The title of the talk', max_length=120, verbose_name='Talk title')),
                ('abstract', wagtail.core.fields.RichTextField(blank=True, help_text='The abstract of the talk')),
                ('speaker_bio', wagtail.core.fields.RichTextField(blank=True, help_text='The bio of the event speaker')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
