# Generated by Django 2.1.15 on 2019-12-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_webcastindexpage_webcastpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcastpage',
            name='talk_title',
        ),
    ]
