# Generated by Django 2.1.15 on 2019-12-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('events', '0011_remove_webcastpage_talk_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcastpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='webcastpage',
            name='image_credit',
            field=models.CharField(blank=True, help_text="Add credit for photo if necessary. Note: add only their name 'Photo courtesy of' is hardcoded", max_length=255),
        ),
        migrations.AlterField(
            model_name='webcastpage',
            name='speaker_name',
            field=models.CharField(help_text='The name of the speaker', max_length=50),
        ),
    ]
