# Generated by Django 2.1.15 on 2020-01-19 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20200119_1402'),
        ('events', '0012_auto_20191215_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcastpage',
            name='moderator',
            field=models.ForeignKey(blank=True, help_text='The moderator of the talk - TIER network person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='network.Person'),
        ),
    ]
