# Generated by Django 2.2.9 on 2020-02-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200219_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcastpage',
            name='video_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
