# Generated by Django 2.2.9 on 2021-06-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventpage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='This image will be used on the Featured Event Block. Ideal dimmensions are 270x180.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
