# Generated by Django 3.1.7 on 2022-01-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20210620_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcastindexpage',
            name='listing_abstract',
            field=models.TextField(blank=True, help_text='Give a brief blurb (about 1 sentence) of what this topic is about. It will appear on other pages that refer to this one.'),
        ),
    ]
