# Generated by Django 3.1.14 on 2023-01-11 18:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('events', '0019_auto_20230111_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='parent_event',
            field=models.ForeignKey(blank=True, help_text='For connecting events under a larger event like a Conference or Symposium', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Ideal dimmensions are 270x180.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='EventPartnerOrganizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_link', models.URLField(blank=True, verbose_name='External link')),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_organizations', to='events.eventpage')),
                ('partner_logo', models.ForeignKey(blank=True, help_text='Partner logo, ideally square', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
