# Generated by Django 2.0.4 on 2018-09-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('main_job_title', models.CharField(blank=True, max_length=255)),
                ('academic_title', models.CharField(blank=True, max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('image_credit', models.CharField(blank=True, help_text="Add credit for photo if necessary. Note: add only their name 'Photo courtesy of' is hardcoded", max_length=255)),
                ('show_in_network', models.BooleanField(default=True)),
                ('show_in_people', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('fellows', 'Fellows'), ('advisory_board', 'Advisory Board'), ('project_directors', 'Project Directors'), ('network_other', 'Network Other')], default='network_other', max_length=255)),
                ('fellowship_year', models.IntegerField(blank=True, choices=[(2010, '2010–2011'), (2011, '2011–2012'), (2012, '2012–2013'), (2013, '2013–2014'), (2014, '2014–2015'), (2015, '2015–2016'), (2016, '2016–2017'), (2017, '2017–2018'), (2018, '2018–2019')], default=2018)),
            ],
        ),
    ]
