# Generated by Django 2.0.4 on 2018-09-21 18:53

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
