# Generated by Django 2.1.3 on 2019-01-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20181011_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='joined_on',
            field=models.DateField(blank=True, help_text='Date this member joined the TIER network. Not publicly visible - used to calculate NEW tags.', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='fellowship_year',
            field=models.IntegerField(blank=True, choices=[(2010, '2010–2011'), (2011, '2011–2012'), (2012, '2012–2013'), (2013, '2013–2014'), (2014, '2014–2015'), (2015, '2015–2016'), (2016, '2016–2017'), (2017, '2017–2018'), (2018, '2018–2019'), (2019, '2019–2020')], null=True),
        ),
    ]
