# Generated by Django 2.1.3 on 2019-04-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20190131_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='academic_title',
            new_name='secondary_job_title',
        ),
    ]
