# Generated by Django 2.0.8 on 2018-09-10 23:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('network', '0005_auto_20180910_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIndexPage2',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('introductory_headline', models.TextField(blank=True, help_text='Introduce the topic of this page in 1-3 sentences.')),
                ('listing_abstract', models.TextField(help_text='Give a brief blurb (about 1 sentence) of what this topic is about. It will appear on other pages that refer to this one.')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Person List Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('fellows', 'Fellow'), ('advisory_board', 'Advisory Board'), ('project_directors', 'Project Director'), ('network_other', 'Network Other')], default='network_other', max_length=255),
        ),
    ]
