# Generated by Django 2.1.3 on 2019-05-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20190418_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tier_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('fellow', 'Fellows'), ('project_director', 'Executive Committee'), ('advisory_board', 'Advisory Board'), ('network_other', 'Network Other')], default='network_other', max_length=255),
        ),
    ]
