# Generated by Django 2.0.4 on 2018-09-13 16:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('network', '0006_auto_20180910_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('introductory_headline', models.TextField(blank=True, help_text='Introduce the topic of this page in 1-3 sentences.')),
                ('listing_abstract', models.TextField(help_text='Give a brief blurb (about 1 sentence) of what this topic is about. It will appear on other pages that refer to this one.')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Network List Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='doe', max_length=255),
            preserve_default=False,
        ),
    ]
