# Generated by Django 2.0.4 on 2018-09-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20180913_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('fellow', 'Fellows'), ('advisory_board', 'Advisory Board'), ('project_director', 'Project Directors'), ('network_other', 'Network Other')], default='network_other', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, help_text='Note: Do not include @', max_length=255),
        ),
    ]
