# Generated by Django 2.1.8 on 2019-05-16 20:16

from django.db import migrations


def migrate_person_categories(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Person = apps.get_model('network', 'Person')
    PersonCategory = apps.get_model('network', 'PersonCategory')

    for person in Person.objects.all():
        category, created = PersonCategory.objects.get_or_create(
            slug=person.category,
            defaults={'title': person.category}
        )
        person.categories.add(category)
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_person_categories'),
    ]

    operations = [
        migrations.RunPython(migrate_person_categories),
    ]
