# Generated by Django 2.2.9 on 2021-06-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20200119_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fellowship_year',
            field=models.IntegerField(blank=True, choices=[(2010, '2010–2011'), (2011, '2011–2012'), (2012, '2012–2013'), (2013, '2013–2014'), (2014, '2014–2015'), (2015, '2015–2016'), (2016, '2016–2017'), (2017, '2017–2018'), (2018, '2018–2019'), (2019, '2019–2020'), (2020, '2020–2021'), (2021, '2021–2022')], null=True),
        ),
    ]
