# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160629_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news items'},
        ),
    ]
