# Generated by Django 2.0.2 on 2018-03-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20180312_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisepage',
            name='listing_excerpt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
