# Generated by Django 2.0.4 on 2018-04-24 18:11

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20180328_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisepage',
            name='course_level_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='+', through='exercises.CourseLevelTag', to='taggit.Tag', verbose_name='course level tags'),
        ),
        migrations.AlterField(
            model_name='exercisepage',
            name='discipline_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='+', through='exercises.DisciplineTag', to='taggit.Tag', verbose_name='discipline tags'),
        ),
        migrations.AlterField(
            model_name='exercisepage',
            name='protocol_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='+', through='exercises.ProtocolTag', to='taggit.Tag', verbose_name='protocol tags'),
        ),
    ]
