# Generated by Django 2.0.2 on 2018-04-24 16:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('exercises', '0004_auto_20180328_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisepage',
            name='all_files',
            field=models.ForeignKey(blank=True, help_text="An archive containing all of this exercise's files.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='exercisepage',
            name='course_level_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='+', through='exercises.CourseLevelTag', to='taggit.Tag', verbose_name='course level tags'),
        ),
        migrations.AlterField(
            model_name='exercisepage',
            name='discipline_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='+', through='exercises.DisciplineTag', to='taggit.Tag', verbose_name='discipline tags'),
        ),
        migrations.AlterField(
            model_name='exercisepage',
            name='protocol_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='+', through='exercises.ProtocolTag', to='taggit.Tag', verbose_name='protocol tags'),
        ),
    ]
