# Generated by Django 2.2.9 on 2020-05-18 20:54

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_auto_20181105_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisepage',
            name='course_level_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='uuid_21ed8698_c4be_4f03_9e26_d7890d9dbb02', through='exercises.CourseLevelTag', to='taggit.Tag', verbose_name='course level tags'),
        ),
        migrations.AlterField(
            model_name='exercisepage',
            name='discipline_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='uuid_faf9c6b3_0e2e_4842_924a_2c3eba5c011b', through='exercises.DisciplineTag', to='taggit.Tag', verbose_name='discipline tags'),
        ),
        migrations.AlterField(
            model_name='exercisepage',
            name='protocol_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='uuid_546dfc75_c901_4551_a441_1a8ddb11886a', through='exercises.ProtocolTag', to='taggit.Tag', verbose_name='protocol tags'),
        ),
        migrations.AlterField(
            model_name='exercisepage',
            name='software_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='uuid_46add48e_c253_4ff8_937a_06719f43e003', through='exercises.SoftwareTag', to='taggit.Tag', verbose_name='software tags'),
        ),
    ]
