# Generated by Django 2.0.2 on 2018-03-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20160901_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowpersonpage',
            name='fellowship_year',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018),
        ),
    ]
