# Generated by Django 2.0.4 on 2018-08-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20180312_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personcategory',
            options={'ordering': ['order', 'title'], 'verbose_name': 'People category', 'verbose_name_plural': 'People categories'},
        ),
        migrations.AddField(
            model_name='personcategory',
            name='order',
            field=models.IntegerField(blank=True, help_text='Lower numbers are shown first. If left blank, it will show up at the end.', null=True),
        ),
        migrations.AlterField(
            model_name='fellowpersonpage',
            name='fellowship_year',
            field=models.IntegerField(choices=[(2010, '2010–2011'), (2011, '2011–2012'), (2012, '2012–2013'), (2013, '2013–2014'), (2014, '2014–2015'), (2015, '2015–2016'), (2016, '2016–2017'), (2017, '2017–2018'), (2018, '2018–2019')], default=2018),
        ),
    ]
