# Generated by Django 2.1.3 on 2019-04-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20180820_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowpersonpage',
            name='fellowship_year',
            field=models.IntegerField(choices=[(2010, '2010–2011'), (2011, '2011–2012'), (2012, '2012–2013'), (2013, '2013–2014'), (2014, '2014–2015'), (2015, '2015–2016'), (2016, '2016–2017'), (2017, '2017–2018'), (2018, '2018–2019'), (2019, '2019–2020')], default=2019),
        ),
    ]
