# Generated by Django 2.1.8 on 2019-05-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaillinkchecker', '0005_auto_20180922_1835'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('people', '0018_auto_20190418_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fellowpersonpage',
            name='personpage_ptr',
        ),
        migrations.RemoveField(
            model_name='fellowshipsindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='fellowshipsindexpage',
            name='related_person_index_page',
        ),
        migrations.DeleteModel(
            name='PersonCategory',
        ),
        migrations.RemoveField(
            model_name='personcategoryrelationship',
            name='category',
        ),
        migrations.RemoveField(
            model_name='personcategoryrelationship',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FellowPersonPage',
        ),
        migrations.DeleteModel(
            name='FellowshipsIndexPage',
        ),
        migrations.DeleteModel(
            name='PersonCategoryRelationship',
        ),
        migrations.DeleteModel(
            name='PersonIndexPage',
        ),
        migrations.DeleteModel(
            name='PersonPage',
        ),
    ]
