# Generated by Django 2.0.4 on 2018-05-11 18:31

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerialspage',
            name='course_title',
        ),
        migrations.AlterField(
            model_name='coursematerialspage',
            name='course_description',
            field=wagtail.core.fields.RichTextField(help_text='1-3 paragraph description of this entry.'),
        ),
        migrations.AlterField(
            model_name='coursematerialspage',
            name='course_name',
            field=models.CharField(help_text='The name of the course this exercise appears in, ex. Statistical and Data Sciences 220', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursematerialspage',
            name='instructor',
            field=models.CharField(help_text='Name of the instructor who teaches this course, ex Janet Black', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursematerialspage',
            name='semester',
            field=models.CharField(help_text='The semester of this course, ex. Spring 2017', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursematerialspage',
            name='university',
            field=models.CharField(help_text='Name of the university this exercise originated from, ex Harvard University', max_length=255),
        ),
    ]
