# Generated by Django 2.0.4 on 2018-05-11 22:11

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_materials', '0002_auto_20180511_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerialsindexpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='1-3 paragraphs explaining the course materials.'),
        ),
    ]
